runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /static
  static_dir: static

- url: /(.*\.(png|mp3|wav))
  static_files: static/\1
  upload: static/(.*\.(png|mp3|wav))

- url: /.*
  script: jumpgym.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest